Issuance on card
bonny-art/bonny-art-backend pull request #21
Opened 2024-10-05 20:43 UTC by Nikolas1790

2024-10-05 22:15 UTC, bonny-art requested changes

2024-10-05 22:15 UTC, bonny-art commented on src/routes/api/pattern-routes.ts
> +  '/pattern/:patternId',
прибери pattern/ з шляху

2024-10-05 22:15 UTC, bonny-art commented on src/controllers/pattern-controllers.ts
> +    const pattern = await patternServices.getPatternById(patternId, language);
рядки
    const pattern = await patternServices.getPatternById(patternId, language);
    if (!pattern) {
      res.status(404).send({ message: 'Pattern not found' });
      return;
    }
   треба винести в мідлвару. це те, про що я тобі казала.
   
   в єтой мідлваре, если нашло схему, то в конце мідлварі записіваешь в req.pattern = pattern (т.е. результат удачного поиска - весь об'єкт нужной схемі)

а потом уе в контрлере ті заново в бд не лезешь, а все нужніе тебе данніе по схеме берешь из єтого об'єкта req.pattern

2024-10-05 22:15 UTC, bonny-art commented on src/controllers/pattern-controllers.ts
> +    if (Array.isArray(languageQuery)) {
а з мовою зробимо не через query, а через params. я розберусь - розкажу. краще для seo

2024-10-05 22:15 UTC, bonny-art commented on src/helpers/widthHeightExtractor.ts
> +export const extractWidthHeight = (
це ти добре зробив, що виніс!

2024-10-05 22:15 UTC, bonny-art commented on src/decorators/isValidId.ts
> +    return next(HttpError(404, `${patternId} is not valid id`));
а чого тут не уккщк повертає? і перенеси це як раз в папку middlewares

2024-10-09 21:30 UTC, bonny-art requested changes
що прийшло в голову - написала. на деякі моменти хочу почути твою думку та аргументи, бо сама не знаю. як краще.

2024-10-09 21:30 UTC, bonny-art commented on src/controllers/pattern-controllers.ts
> +    if (!pattern) {
якщо не буде петтерн, то мідлвара до цього контролера вже не пустить. не бачу сенсу у цій перевірці.

2024-10-09 21:30 UTC, bonny-art commented on src/controllers/pattern-controllers.ts
> +  req: RequestWithPattern & { params: { language: string; patternId: string } },
чому ти & { params: { language: string; patternId: string } } не додав зо інтерфейсу? Я не знаю, як правильно. тут хочу знати твою думку з цього приводу.

2024-10-09 21:30 UTC, bonny-art commented on src/services/pattern-services.ts
> +export const getPattern = async (pattern: PatternDb, language: Language) => {
getPatternData - назви так цей сервіс

2024-10-09 21:30 UTC, bonny-art commented on src/services/pattern-services.ts
> +        id: pattern._id.toString(),
зміни порядок полів
![image](https://github.com/user-attachments/assets/88cd15ee-aaa1-4ccf-a7ee-63d528ab1f3a)

2024-10-09 21:30 UTC, bonny-art commented on src/middlewares/isValidId.ts
> +const isValidId = (req: Request, res: Response, next: NextFunction) => {
а давай ми це з мідлварів перенесемо у хелпери. і будемо в isValidId приймати ід параметром, а повертати тру чи фолс. і потім де треба (в цьому випадку в мідлварі checkPatternExists викликати і перевіряти. і помилку кидати вже там. бо нам буде потрібно перевіряти різні ід.

2024-10-09 21:30 UTC, bonny-art commented on src/middlewares/checkPatternExists.ts
> +    const patternDoc = await patternServices.getPatternById(patternId);
я би тут назвала pattern

2024-10-09 21:30 UTC, bonny-art commented on src/middlewares/checkPatternExists.ts
> +    const pattern = {
а навіщо ти приводиш до рядка? не можна десь далі, якщо воно свариться, врахувати, що там обджектІд і типізувати його так?

2024-10-09 21:51 UTC, Nikolas1790 commented on src/controllers/pattern-controllers.ts
> +  req: RequestWithPattern & { params: { language: string; patternId: string } },
добавил интерфайс

2024-10-09 23:14 UTC, bonny-art requested changes

2024-10-09 23:14 UTC, bonny-art commented on src/helpers/isValidId.ts
> +const isValidId = (req: Request, res: Response, next: NextFunction) => {
а,  вже зрозуміла. тут самої лоіки перевірки - 1 рядок, а саме виклик методу монгуз. 

дивись, в мідлваре це не бачу сенсу виносити, бо тоді нам потрібно буде на кожен вид ід робити окрему мідлвару, яка буде брати його за назвою з параметрів. const { patternId } = req.params; - тут же буде потрібно кожен раз прописувати, чи це patternId, чи userId, чи ще якийсь id, як він буде називатись у нас в шляху.

я думала, що тут багато логіки, і тому запропонувала винести її, логіку, у хелпер звичайною функцією (не мідлварою) і вже потім викликати її у тіж же мідлварі, що буде перевіряти, чи є такий документ. тобто перед викликом сервісу getPattenById думала викликати цей хелпер і, якщо це не валіднй обджект ід, то кидати помилку, вже не роблячи запил до БД.

але тут логіки факточно немає, тому пропоную взагалі цей файл видалити, а просто оцю перевірку 
if (!isValidObjectId(patternId)) {
    return next(HttpError(404, `${patternId} is not valid id`));
  }
робити в мідлварі перед викликом сервісу getPattenById

2024-10-09 23:14 UTC, bonny-art commented on src/middlewares/checkPatternExists.ts
> +    const patternDoc = await patternServices.getPatternById(patternId);
а от перед цим рядком додай цю перевірку:
if (!isValidObjectId(patternId)) {
return next(HttpError(404, ${patternId} is not valid id));
}

2024-10-10 23:10 UTC, bonny-art approved these changes

2024-10-10 23:11 UTC, merged