Update user
bonny-art/bonny-art-backend pull request #40
Opened 2024-10-23 14:46 UTC by Nikolas1790

2024-10-23 23:02 UTC, bonny-art requested changes

2024-10-23 23:02 UTC, bonny-art commented on src/db/models/User.ts
> +      'UserName must contain only letters, spaces, or hyphens (e.g., John Doe)',
та апостроф

2024-10-24 21:20 UTC, Nikolas1790 commented on src/controllers/auth-controler.ts
> +    const user = await User.findById(_id);
справедливое замечание

2024-10-24 23:29 UTC, bonny-art approved these changes

2024-10-24 23:29 UTC, merged