Submit form data
bonny-art/bonny-art-backend pull request #69
Opened 2024-12-16 13:48 UTC by Nikolas1790

2024-12-16 23:44 UTC, bonny-art requested changes

2024-12-16 23:44 UTC, bonny-art commented on src/controllers/form-controllers.ts
> +      message: 'Форма успішно відправлена',
мабуть треба англійською. у нас всі повідомлення на фронт англійською

2024-12-16 23:44 UTC, bonny-art commented on src/controllers/form-controllers.ts
> +    const newFormData = await FormData.create({
винеси у сервіси

2024-12-16 23:44 UTC, bonny-art commented on src/db/models/form.schema.ts
> +    message: { type: String, required: true },
Давай обмежимо довжину у 500 символів

2024-12-16 23:44 UTC, bonny-art commented on src/db/models/form.schema.ts
> +const formSchema = new mongoose.Schema(
пропоную назвати contactForm.schema. І, відповідно модель також переназви. Бо може будуть потім якісь ще інші форми, щоб розрізняти.

2024-12-16 23:44 UTC, bonny-art commented on src/db/models/form.schema.ts
> +  message: Joi.string().required(),
Також додай обмеження довжини

2024-12-16 23:44 UTC, bonny-art commented on src/helpers/mail-templates.ts
> +export const getNewMessageEmailContent = (
я боюсь, якщо буде постійно призходити через нодемейлер повідомлення на один і той самій імейл, то скоро нодемейлер заблокує можливість надсилання, бо буде вважати це спамом чи чимось подібним. 

Я думала ти знайдеш якийсь інший спосіб :)

Тому, або давай тоді на телеграм це переробимо. Або можеш подивитись такий сервіс:

3. Brevo (колишній Sendinblue)
Опис: Сервіс для відправки email із бекенду через SMTP або API. Безкоштовний план до 300 листів на день.

Особливості:

Зручний API та SMTP.
Безкоштовний план з обмеженням на кількість листів.
Проста інтеграція у Node.js або Python.
Приклад використання:

Зареєструйтесь у Brevo та отримайте SMTP ключі.
Використовуйте Nodemailer для відправки листів.
ts
Copy code
const transporter = nodemailer.createTransport({
  host: "smtp-relay.sendinblue.com",
  port: 587,
  auth: {
    user: "your-brevo-username",
    pass: "your-smtp-password",
  },
});
Сайт: https://www.brevo.com/

я не знаю, не дивилась. інформацію надав чат гпт.

2024-12-16 23:44 UTC, bonny-art commented on src/controllers/form-controllers.ts
> +export const submitFormData = async (
тут так само зроби, щоб із назви було зрозуміло. що це саме CintactForm. в сервісі нижче - також

2024-12-16 23:44 UTC, bonny-art commented on src/routes/index.ts
>  const router = express.Router();
попробуй тут додати такий параметр:
= express.Router({ mergeParams: true });

а потім /:language винести на рівень вище, в app.ts в цей рядок після api:
app.use('/api', routes);

якщо все буде праювати, так і залиш. якщо ні - то вже тоді як було поверни.

2024-12-16 23:44 UTC, bonny-art commented on src/types/submit-form-data-types.ts
> +export interface checkSubmitFormDataRequest extends setLanguageRequest {
тут так само уточни у назві, що це саме ContactForm

2024-12-17 12:52 UTC, Nikolas1790 commented on src/helpers/mail-templates.ts
> +export const getNewMessageEmailContent = (
нодемейлер точно незаблокирует отправку это же библиотека, Наверное телеграм будет самым 
оптимальным способом

2024-12-18 23:20 UTC, bonny-art commented on src/db/models/contact-form.schema.ts
> +export const FormData = mongoose.model('FormData', contactFormSchema);
'FormData' також заміни на 'ContactForm' - це так буде називатись колекція в БД

2024-12-18 23:20 UTC, bonny-art commented on src/helpers/mail-templates.ts
> +export const getNewMessageEmailContent = (
телеграм да, пусть будет.
но я не помню, вроде ж расказівала еще тогда при Лане. на финальном на курсах я делала такую отправку через нодемейлер. и тестировала. отправляя себе на почту сообщения. в результате оно в какой-то моент перестало отправлять.. а писала ошибку, мол изза того, что ваше сообщение расценено как спам. мі не будем отправлять. и насколько я поняла, єто блокировал именно нодемейлер. если на разніе почті, то типа ок, а на одну и ту же - уже плохо, типа спасишь один аккаунт.

мне пришлось срочно создавать новую почту, чтобі сдать проект и показать все на презентации.

2024-12-18 23:47 UTC, bonny-art requested changes

2024-12-18 23:47 UTC, bonny-art commented on src/controllers/contact-form-controllers.ts
> +    await sendEmail(email, null, 'newMessage', lang, {
раз вирішили зупинитись на телеграмі, то листа тоді прибери.

2024-12-18 23:47 UTC, bonny-art commented on src/controllers/contact-form-controllers.ts
> +    await sendTelegramMessage('newMessage', lang, {
імпортуй, бццдь ласка, через зірочку 
import * as telergamServices from.... 
і потім тут використай як об'єкт з властивістью. як у рядку 23 цього файлу

2024-12-18 23:47 UTC, bonny-art commented on src/controllers/contact-form-controllers.ts
цей файл назви, будь ласка, просто форм контроллерз, нехай тут будуть всі контролери, що власне до форм будуть відноситись. просто в назві контролерів вже будемо уточнювати, до якої саме форми він відноситься.

2024-12-18 23:47 UTC, bonny-art commented on src/services/contact-form-services.ts
цей файл назви, будь ласка, просто форм сервісез, нехай тут будуть всі сервіси, що власне до форм будуть відноситись. просто в назві сервісів вже будемо уточнювати, до якої саме форми він відноситься.

2024-12-18 23:47 UTC, bonny-art commented on src/types/submit-contact-form-data-types.ts
тут так само, можна файл назвати просто форм-тайпз. і будемо сюда типи по всіх формах

2024-12-18 23:47 UTC, bonny-art commented on src/helpers/telegram-templates.ts
> +    📝 **Нове повідомлення з контактної форми**:
це тобі, мабуть, чат ГПТ іконочки понакидував на кожний рядочок? :)

не потрібно робити різні повідомлння в залежності від мови юзера. ці повідомлення мені. тому заголовки рядків тлільки українською. а текс - як прийшов.

2024-12-18 23:47 UTC, bonny-art commented on src/services/send-telegram-services.ts
дивись. у нас є файл telegram-service.ts, в якому є сервіс, який зараз використовується для відправки даних замовлення. навіщо ти створюєш окремий файл? я думаю, що варто цей сервіс розмістити також у файлі telegram-service.ts.

і я не думаю, що в залежності від мови користувача надсилати мені повідомлення треба із заголовками рядків різними мовами. думаю, мені буде достатньо тільки україннськї для заголовків рядків у повідмленні. а текст вже як прийшов.

тому, може і не треба буде тобі другого сервісу, а просто будеш використовувати вже той, о є, просто передаючи йому повідомлення для формування якого не потрібно буде визначати мову?

тоді в контролері викликаєш функцію, що бде створювати потрібне повідомлення,  і викликаєш  sendOrderToTelegram сервіс, куди передаєш повідомлення. можна його переіменувати в сендМесседжТуТелеграм

тоді треба буде створити функцію для формування повідомлення для замовлення. і так само у контролері замовлення її викликати, отримувати повідомлення, яке відправляти до сервісу sendOrderToTelegram

2024-12-19 21:10 UTC, bonny-art approved these changes

2024-12-19 21:10 UTC, merged